name:                hagame
version:             0.1.0.0
github:              "jordanemedlock/hagame"
license:             BSD3
author:              "Jordan Medlock"
maintainer:          "jordanemedlock@gmail.com"
copyright:           "2020 Jordan Medlock"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jordanemedlock/hagame#readme>

dependencies:
- base >= 4.7 && < 5
- rio >=0.1.18 && <0.2
- bytestring >=0.10 && <1
- GLFW-b >=3.3 && <4
- OpenGL >=3.0 && <4
- bindings-GLFW >=3.3 && <4
- matrix >=0.3 && <0.4
- vector >=0.12 && <0.13
- JuicyPixels >=3.3 && <4
- filepath >=1.4 && <2
- time >=1.9 && <2
- freetype2 >=0.2 && <0.3
- containers >=0.6 && <0.7

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- BlockArguments

library:
  source-dirs: src
  exposed-modules: Graphics.Game.Hagame

tests:
  hagame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hagame
